# Generated by Django 4.1.6 on 2023-02-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=128, null=True)),
                ('major', models.CharField(max_length=128, null=True)),
                ('gender', models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True)),
                ('mbti', models.CharField(choices=[('INFJ', 'INFJ'), ('ISFJ', 'ISFJ'), ('ESFJ', 'ESFJ'), ('ENTP', 'ENTP'), ('ESFP', 'ESFP'), ('INTJ', 'INTJ'), ('ESTJ', 'ESTJ'), ('INTP', 'INTP'), ('ENFJ', 'ENFJ'), ('ISFP', 'ISFP'), ('ESTP', 'ESTP'), ('ISTJ', 'ISTJ'), ('ENTJ', 'ENTJ'), ('ENFP', 'ENFP'), ('ISTP', 'ISTP'), ('INFP', 'INFP')], max_length=16, null=True)),
                ('age', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
