# Generated by Django 4.1.6 on 2023-02-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESFJ', 'ESFJ'), ('ENTJ', 'ENTJ'), ('INTP', 'INTP'), ('ISFP', 'ISFP'), ('INFP', 'INFP'), ('INTJ', 'INTJ'), ('ISTP', 'ISTP'), ('ISFJ', 'ISFJ'), ('ESFP', 'ESFP'), ('INFJ', 'INFJ'), ('ENFP', 'ENFP'), ('ESTP', 'ESTP'), ('ISTJ', 'ISTJ'), ('ENFJ', 'ENFJ'), ('ESTJ', 'ESTJ'), ('ENTP', 'ENTP')], max_length=16, null=True),
        ),
    ]
