# Generated by Django 4.1.6 on 2023-02-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', '여성'), ('male', '남성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ISTP', 'ISTP'), ('ESFP', 'ESFP'), ('ESTP', 'ESTP'), ('ISFJ', 'ISFJ'), ('INFP', 'INFP'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ENTP', 'ENTP'), ('ISFP', 'ISFP'), ('ESTJ', 'ESTJ'), ('ISTJ', 'ISTJ'), ('INTJ', 'INTJ'), ('ESFJ', 'ESFJ'), ('INTP', 'INTP'), ('INFJ', 'INFJ'), ('ENTJ', 'ENTJ')], max_length=16, null=True),
        ),
    ]
