# Generated by Django 4.1.6 on 2023-02-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_gender_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESFP', 'ESFP'), ('ENTJ', 'ENTJ'), ('ESTP', 'ESTP'), ('ESTJ', 'ESTJ'), ('INTP', 'INTP'), ('ISFJ', 'ISFJ'), ('INFP', 'INFP'), ('ENFP', 'ENFP'), ('INTJ', 'INTJ'), ('ESFJ', 'ESFJ'), ('INFJ', 'INFJ'), ('ENTP', 'ENTP'), ('ISFP', 'ISFP'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('ENFJ', 'ENFJ')], max_length=16, null=True),
        ),
    ]
