# Generated by Django 4.1.6 on 2023-02-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_gender_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENFJ', 'ENFJ'), ('ISFP', 'ISFP'), ('ESFP', 'ESFP'), ('ISTP', 'ISTP'), ('INTJ', 'INTJ'), ('ESTJ', 'ESTJ'), ('ENFP', 'ENFP'), ('INTP', 'INTP'), ('INFJ', 'INFJ'), ('ISFJ', 'ISFJ'), ('ESFJ', 'ESFJ'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('INFP', 'INFP'), ('ESTP', 'ESTP'), ('ISTJ', 'ISTJ')], max_length=16, null=True),
        ),
    ]
