# Generated by Django 4.1.6 on 2023-02-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', '여성'), ('male', '남성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESTJ', 'ESTJ'), ('ISTJ', 'ISTJ'), ('INTP', 'INTP'), ('ISTP', 'ISTP'), ('ENTJ', 'ENTJ'), ('ISFP', 'ISFP'), ('ENTP', 'ENTP'), ('INFJ', 'INFJ'), ('ENFP', 'ENFP'), ('ESTP', 'ESTP'), ('ESFJ', 'ESFJ'), ('INFP', 'INFP'), ('INTJ', 'INTJ'), ('ESFP', 'ESFP'), ('ISFJ', 'ISFJ'), ('ENFJ', 'ENFJ')], max_length=16, null=True),
        ),
    ]
